table Sheet1
	lineageTag: 6df784d7-4015-44d2-9ce0-c2a38cd1915c

	column 'Row ID+O6G3A1:R6'
		dataType: int64
		formatString: 0
		lineageTag: 97d27b94-d00a-43c7-ab6a-aec5c2ff8b42
		summarizeBy: sum
		sourceColumn: Row ID+O6G3A1:R6

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 4eb1ce7a-3e17-4fca-a282-b63beb26f9b2
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc013b49-cdf8-41c8-bb25-b694fbc1c8d5
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 9dc5fe3f-2440-43ab-bee6-d265dd6833dc
			defaultHierarchy: LocalDateTable_89e11a7f-e152-4e9f-8a4e-6d8f453012a3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 48a35805-42d4-4292-a7f2-b8e31923edce
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 2f068e48-26cc-4f76-89de-a7d3caeb1119
			defaultHierarchy: LocalDateTable_89620c03-1778-4d26-9a21-26c489fea557.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: c067921c-e614-469c-8109-c5c35b5aa3fb
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 29f5d197-b141-402b-8648-aafe5717c63f
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 884df724-fa96-4726-bfa7-faa9088a84d9
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 6acf6411-a59b-4047-b2cb-97bc49e3abba
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6f2f75f7-014d-40ad-8741-6c18bc7a1705
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 451af604-bd92-4e93-8988-cf0ac9d15970
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 93d7b697-ce56-457b-b45b-a7ee82a58f70
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 780b4b60-2195-4a6a-9a20-f504cd15613f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: c255debb-81b5-4645-9321-8cb481b9def3
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d3fdc076-39cc-4144-945a-22df0a817837
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 8b95e6d5-9811-46df-a260-cd19f1fbc621
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: c8ca125c-2a9b-4ba0-99f7-1dd6b98eaa4d
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: fc7f0aa1-fdd0-4565-ae50-7f1ebabd421b
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 0af48580-4da7-4755-b08b-cab87adeef91
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		lineageTag: 12c5aab9-e12d-432a-b421-91a846595e37
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Returns
		dataType: int64
		formatString: 0
		lineageTag: 711953ae-7bab-4602-9263-d367b4902926
		summarizeBy: sum
		sourceColumn: Returns

		annotation SummarizationSetBy = Automatic

	column 'Payment Mode'
		dataType: string
		lineageTag: 4de64a81-a486-4c83-9c2a-fed9658ac6ae
		summarizeBy: none
		sourceColumn: Payment Mode

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Dell\Downloads\Amazon Store Sales Data.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID+O6G3A1:R6", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Profit", type number}, {"Returns", Int64.Type}, {"Payment Mode", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

